---
title: "Downloads"
description: |
  Current and past versions of FTOL available for download
bibliography: references.yaml
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About the data

### Tree format

FTOL is available in several flavors:

- The maximum likelihood (ML) tree has branchlengths in units of expected genetic change per site.
- The consensus tree is the extended majority-rule consensus of the bootstrap trees, with units in expected genetic change per site. 
- The dated tree has branchlengths in units of time (Ma) and is ultrametric.
- The backbone ML tree only includes species that have complete plastome sequences available.

All trees are rooted on algae (*Zygnema*) and include outgroup taxa, but *Zygnema* has been pruned from the dated trees. Node labels are bootstrap support values (%) measured with ultra-fast bootstrap [@Hoang2018].

All trees are in [Newick format](https://en.wikipedia.org/wiki/Newick_format).

### Other data files

The tree files are provided as part of a data archive (zip or tar.gz format).

Other files in the archive include DNA sequence alignments, GenBank accession numbers, and fossil calibration points.

All files are described in the README.txt file contained within the archive.

## `ftolr` R pacakge

For reading the data directly into R with more options (rooting, inclusion of outgroup, selection of only part of the alignment, etc.), use the [ftolr R package](https://github.com/fernphy/ftolr).

## Current version: v`r ftolr::ft_data_ver()`

Built with data from GenBank release 249 (cutoff date 2022-04-15).

- [zip](https://github.com/fernphy/ftol_data/archive/refs/tags/v1.1.0.zip)
- [tar.gz](https://github.com/fernphy/ftol_data/archive/refs/tags/v1.1.0.tar.gz)

## Past versions

### v1.0.0

Cutoff date 2021-12-31. Does not include algae and was rooted on bryophytes.

- [zip](https://github.com/fernphy/ftol_data/archive/refs/tags/v1.0.0.zip)
- [tar.gz](https://github.com/fernphy/ftol_data/archive/refs/tags/v1.0.0.tar.gz)

### v0.0.1

Hosted on FigShare and lacks some of the tree formats above due to changes in methodology.

- [FTOL v0.0.1](https://figshare.com/articles/dataset/Fern_Tree_of_Life_v0_0_1/13251290)
